### PR TITLE
Replace uses of  public fields with their associated getter methods.

### PR DESCRIPTION
**Pull request by nreid260**

### CODE REVIEW

**Comment by Yannic** [comment]
Thanks! I'm assuming this is working towards #411.
What do we need to get the tests to pass? Update closure-compiler to `v20190909`?

**Comment by nreid260** [comment]
It's more like an example of the difficulty described by that issue. The fact that I need to make this PR at all is what we consider problematic.

I think updating to `v20190909` is all that should be needed. That version has both the getters and the public fields.

**Comment by Yannic** [comment]
We updated closure compiler to `v20190909`. Can you rebase so we can see if the tests pass?

**Comment by nreid260** [comment]
Done

**Pull request merged**
