### PR TITLE
Retire Travis in favor of Buildkite

### PR DESCRIPTION
**Pull request by Yannic**
This PR retires Travis in favor of Buildkite.

### CODE REVIEW

**Comment by Yannic** [comment]
Seems like Bazelisk is running into GitHub rate limiting on Travis.

//cc @philwo

**Comment by philwo** [comment]
@Yannic I can think of three ways to fix this:
- Don't use Travis ;)
- Create a non-privileged GitHub user, get an API token for it, pass that token to Bazelisk via the `BAZELISK_GITHUB_TOKEN` environment variable. Then you should no longer run into rate limiting.
- Implement https://github.com/bazelbuild/bazelisk/issues/87, then we no longer use the GitHub API to figure out the latest release, so rate limiting will no longer happen.

**Comment by Yannic** [comment]
I'm voting for removing Travis. It's slow and doesn't provide anything we can't get from Buildkite.

@gkdn @dslomov @laurentlb WDYT?

**Comment by alexeagle** [comment]
Sounds great @Yannic 

Can you check that all the tests run on Travis are also run on buildkite, so we know we don't lose any coverage? And update the PR to just remove the travis config.

**Comment by Yannic** [comment]
We're running the same tests on Buildkite as we run on Travis (`//...`), and, IIUC, sandboxing is the default these days.

Someone with write (or even admin) access needs to remove that Travis is a required check for PRs before we can delete the config. @dslomov @laurentlb Can one of you handle this?

**Comment by philwo** [comment]
@Yannic Done :)

**Comment by Yannic** [comment]
@alexeagle Done. ptal

**Pull request merged**
