### PR TITLE
Remove deprecated Bazel features

### PR DESCRIPTION
**Pull request by jjudd**
This makes rules_closure compatible with `--all_incompatible_changes`, best I can tell.

### CODE REVIEW

**Comment by jjudd** [comment]
I was updating our internal version of Bazel to 0.16 and these errors showed up with `--all_incompatible_changes` enabled, so I fixed them.

**Comment by JaredNeil** [comment]
Yes, I'm aware of this PR and intended to add that commit.

**Comment by jjudd** [comment]
I am ok with my commits being contributed to this project.

**Comment by laurentlb** [comment]
ping @dslomov

**Comment by dslomov** [comment]
Sorry for delay, I'll be taking a look now

**Pull request merged**
