### PR TITLE
Replace native {http,git}_archive with Skylark rules

### PR DESCRIPTION
**Pull request by davido**
See [1] for more details.

Closes: #272.

Test Plan:

* Apply this CL on Bazel master: [2] and build bazel
* Run with this custom built bazel version:

  $ bazel test //javatests/...
  $ bazel test //closure/...

[1] https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
[2] https://bazel-review.googlesource.com/#/c/bazel/+/55932/

### CODE REVIEW

**Comment by jart** [comment]
Could this change be updated to use the `filegroup_external` that's in this repository?

**Comment by davido** [comment]
@jart It seems that `filegroup_external` is staled and not used any more, since d3e0437b6964db0719d71f075833614df3348fa7, where downloading of custom-downloaded dependencies for different platforms was replaced with standard `@com_google_protobuf//:protoc`. I guess it can now be cleaned up.

**Comment by davido** [comment]
> I guess it can now be cleaned up.

Done in: https://github.com/bazelbuild/rules_closure/pull/273.

**Comment by jart** [comment]
You're correct it's dead code here, but I've found it exceedingly useful for the TensorBoard codebase: https://github.com/tensorflow/tensorboard/blob/master/third_party/js.bzl#L25

**Comment by jart** [comment]
Speaking as the author of [Bazel's core HTTP download routines](https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d), I do not support [`@bazel_tools//build_defs/repo:http.bzl`](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl) being used as a public API, and I've had no involvement in its development. I was under the impression that file was introduced back in 2016 to serve as example code. It has technical, design, and feature issues that would need to be addressed before it'd be appropriate to recommend as a canonical approach.

**Comment by dslomov** [comment]
@jart I am not aware of any "issues" with Skylark reimplementation of http_archive. It is fully functionaly equivalent to native http_archive. Bazel team recommends Skylark implementation of http_archive.

**Comment by dslomov** [comment]
As discussed on #272 (see my https://github.com/bazelbuild/rules_closure/issues/272#issuecomment-396550532) regardless of whether native http_archive has any features that do not exist in Skylark version of it, those features are not used in rules_closure repository.  Also, Skylark version uses the same HTTP download routines as the native version.

I see no reason to block this pull request.

**Comment by dslomov** [comment]
My intent is to merge this PR tomorrow unless there are motivated objections (pertaining to use of `http_archive` in this project)

**Comment by dslomov** [comment]
(build failures reported are infrastructure failures on Bazel CI - looking into it)

**Comment by Yannic** [comment]
@dslomov @jart Any update on this?

**Pull request closed without merging**
