### PR TITLE
Update protobuf version to 3.8.0

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Comment by davido** [comment]
> #  "https://mirror.bazel.build/github.com/google/protobuf/archive/v3.7.1.tar.gz",

@meteorcloudy @laurentlb 

Can you please upload v3.8.0.tar.gz to mirror.bazel.build? Thanks.

**Comment by meteorcloudy** [comment]
It's done, both `v3.8.0.tar.gz` and `v3.8.0.zip` are available.

But, note that this is still some incompatible migration needed from protobuf. See https://github.com/protocolbuffers/protobuf/pull/6206. TensorFlow is failing due to this, not sure this will affect rules_closure as well.

**Comment by davido** [comment]
@meteorcloudy Thanks. I will adapt this PR. Concerning the link to Protobuf PR: I have tested rules_closure and it worked as is with Protobuf 3.8.0.

**Comment by davido** [comment]
> I will adapt this PR.

Done. PTAL.

**Pull request merged**
