### PR TITLE
Update protobuf version to 3.9.0

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Comment by davido** [comment]
@laurentlb @meteorcloudy Can you please upload v3.8.0.tar.gz to mirror.bazel.build?

**Comment by meteorcloudy** [comment]
@davido Do you mean protobuf v3.9.0?

**Comment by meteorcloudy** [comment]
The following artifacts are now available:
https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.8.0.tar.gz
https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.9.0.tar.gz
https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/protobuf-all-3.8.0.tar.gz
https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/protobuf-all-3.9.0.tar.gz

**Comment by Yannic** [comment]
@davido Can we roll to branch `3.9.x` with `92f2c8956711175f6d892a9244a7311b39948800` instead? This will include fixes for `--incompatible_load_{cc,java,proto}_rules_from_bzl` which didn't make it into `3.9.0`.

**Comment by davido** [comment]
> Do you mean protobuf v3.9.0?

@meteorcloudy Thanks. Yes I meant v3.9.0.

**Comment by davido** [comment]
> Can we roll to branch 3.9.x with 92f2c8956711175f6d892a9244a7311b39948800 instead?

@Yannic I would rather do it in its own PR (or, alternatively we could wait until 3.10 release).

**Pull request merged**
