### PR TITLE
Support conformance configs

### PR DESCRIPTION
**Pull request by hochhaus**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by hochhaus** [comment]
Hi @jart. Any time to review #135, #136 and #137?

**Comment by jart** [comment]
LGTM. I've been meaning to do this.

Also, as soon as I get a chance, I'm going to open source the standard conformance configs that we use internally at Google.

**Comment by hochhaus** [comment]
> I'm going to open source the standard conformance configs that we use internally at Google.

Outstanding!

**Pull request merged**
