### PR TITLE
Fix Travis configuration

### PR DESCRIPTION
**Pull request by jart**

### CODE REVIEW

**Comment by pcj** [comment]
Looks much cleaner, nice.  I'm still concerned this will fail if the installer has a different name however.  I've adopted this:

```
 - if [[ "$V" == "HEAD" ]]; then CI_ARTIFACT="`wget -qO- $CI_BASE | grep -o 'bazel-[-_a-zA-Z0-9\.]*-installer.sh' | uniq`"; fi
```

Reference:
https://github.com/pubref/rules_protobuf/blob/master/.travis.yml

**Comment by jart** [comment]
If it has a different name for HEAD, I'll just update the configuration again, or put pressure on Bazel team to keep the name deterministic. The grep matching with that pattern is a little difficult to get right, as we've discovered.

**Comment by pcj** [comment]
SGTM to keep the name deterministic.

**Comment by jart** [comment]
Fixed in https://github.com/bazelbuild/rules_closure/commit/45b4f737b879cb489ff143d29b67b916eca5e76e

**Pull request closed without merging**
