### PR TITLE
Update upstream versions of soy & related packages

### PR DESCRIPTION
**Pull request by hochhaus**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by hochhaus** [comment]
@jart Once #124 & #125 are merged could do a new release?

**Comment by jart** [comment]
Mr. Jenkins: test this please

**Comment by jart** [comment]
We can absolutely cut a release. But we should also upgrade Closure Compiler and friends to v20160822 beforehand. I can take care of that this week unless you'd prefer to send a PR upgrading them.

**Comment by hochhaus** [comment]
If you are willing to update them that sounds good to me. :) I'm not in a rush for the new release.

**Comment by jart** [comment]
It seems like I discovered a bug on GitHub. I clicked the button to prepare to merge. Then navigated away, hit back button, and then hit merge. For some reason, it gave all the credit for your work to me: https://github.com/bazelbuild/rules_closure/commit/ee88f2225f5b1fea98c9979803d25372cb086ef4 This makes me sad :(

**Comment by hochhaus** [comment]
No worries. I'm not worried about the credit at all. I'm just happy to have soy PB support. That wouldn't have happened (nearly this quickly) without your efforts to organize the push. Thanks!

**Pull request merged**
