### PR TITLE
Remove calls to deprecated `setFeatureSet(FeatureSet)` which does not…

### PR DESCRIPTION
**Pull request by rishipal**
…hing and will be deleted

### CODE REVIEW

**Review by soldair — APPROVED** [review]
lgtm

**Comment by rishipal** [comment]
This PR causes this breakage. It's happening because the internal PassFactory.java contains the `setFeatureSet` in its builder class.

```
java.lang.IllegalStateException: Missing required properties: featureSet
--
  | at com.google.javascript.jscomp.AutoValue_PassFactory$Builder.autoBuild(AutoValue_PassFactory.java:150)
```
I think I should land the internal change which deletes the `setFeatureSet` method first, and then immediately fix the upstream. What do you think?

**Comment by gkdn** [comment]
@rishipal You can land the internal change. There is another similar change that was submitted internally. 

I will fix them together in the opensource with the next update.

**Comment by gkdn** [comment]
Submitted in https://github.com/bazelbuild/rules_closure/commit/6bbbfc7d80474a6a1a4491da7b601c0cab440b07

**Pull request closed without merging**
