### PR TITLE
ppc64le support for filegroup_external

### PR DESCRIPTION
**Pull request by jayfurmanek**
This PR adds support for an alternate Linux arch: `ppc64le`.

A new function `_linux_arch_value` is added to check `uname -m` if the platform is determined to be `Linux`. In the event that the arch is `ppc64le`, then the `_merge` is done with two new defines:
`sha256_urls_ppc64le` 
`sha256_urls_extract_ppc64le`

This code can be easily extended to provide support for the `aarch64` arch as well if ever needed.

### CODE REVIEW

**Comment by jayfurmanek** [comment]
Hi @jart ! Any thoughts thoughts on this one? A reviewer wasn't assigned, so I'm a little unsure of the process. I can get a matching issue open, if needed.

`rules_closure` is used by Tensorboard, so I'm hoping to get this PR in so I can fix a final issue there on getting TB working for ppc64le.

thanks!

**Comment by jayfurmanek** [comment]
@Yannic @davido Sorry to spam reviewers, but I was hoping to get this one reviewed and merged if you're accepting contributions.

Thanks! Let me know if I skipped some other process.

**Comment by davido** [comment]
LGTM, so note, that I don't have admin ACL on this repository. Pinging current maintainers:

//CC @gkdn @dslomov @buchgr

**Comment by jayfurmanek** [comment]
Thanks! Much appreciated!

**Comment by jayfurmanek** [comment]
Thanks @dslomov !

**Pull request merged**
