### PR TITLE
Allow a closure_js_proto_library src to expand to multiple files

### PR DESCRIPTION
**Pull request by flamingcow66**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by flamingcow66** [comment]
I signed it!

**Comment by jart** [comment]
Mr. Jenkins: test this please

**Comment by jart** [comment]
Thank you for taking the time to send us this bug fix Flaming Cow.

LGTM

Feel free to send us a follow-up pull request adding yourself to the CONTRIBUTORS file.

**Pull request merged**
