### PR TITLE
Migrate protobuf info provider to new-style one.

### PR DESCRIPTION
**Pull request by philwo**
This migrates the provider containing information about protocol buffers from the old-style 'dep.proto' pattern to the new-style 'dep[ProtoInfo]' one.

### CODE REVIEW

**Comment by dslomov** [comment]
> @dslomov Any idea why the tests fail?

I guess ProtoInfo is not in released Bazel, right @lberki ?

**Comment by lberki** [comment]
We had apparently just had a release!

**Comment by philwo** [comment]
Rebased. Tests should pass now that we have Bazel 0.22.0 available everywhere.

**Comment by philwo** [comment]
Yay, all tests pass - @dslomov can you approve and merge?

**Comment by dslomov** [comment]
I'll import this

**Pull request merged**
