### PR TITLE
closure_js_binary: support multiline output_wrappers via --output_wrapper_file

### LINKED ISSUE #399: closure_js_binary: output_wrapper for adding sourceMappingURL
With plovr, we had been using output_wrapper to add the sourcemap URL to compiled binaries:

```
  "output-wrapper": "(function(){%output%})();\n//# sourceMappingURL=/sourcemap?id=users_dev\n"
```

When I try the same thing with `closure_js_binary`:
```
closure_js_binary(
    name = "users_dev",
    compilation_level = "SIMPLE",
    language = "ECMASCRIPT5",
    output_wrapper = "(function(){%output%})();\n//# sourceMappingURL=/sourcemap?id=users",
```

I get an error: 
```
java.lang.IllegalArgumentException: a source must have a name
```

I believe this is due because the output_wrapper is not properly quoted in the command line that gets built up. If I try to quote it myself by adding a single quote to the beginning and end:
```
    output_wrapper = "'(function(){%output%})();\n//# sourceMappingURL=/sourcemap?id=users'",
```

I get a different error:
```
java.lang.RuntimeException: Cannot read code of a source map's source file.
Caused by: java.nio.file.NoSuchFileException: /# sourceMappingURL=/s/users/public/js/users.js.map'
```

If I escape the \n, then I end up with a literal \n in the JS file.

Should I look at submitting a pull request + fix for this? How do others add the sourcemap URL to the end of the file?

### PR DESCRIPTION
**Pull request by robfig**
Fixes #399

I believe it's not possible without using the --output_wrapper_file parameter and using that is difficult without adding support to this library itself (it can't be done in a macro, and composing rules is hard within a rule).

Ref
https://groups.google.com/forum/#!searchin/bazel-discuss/multiline%7Csort:date/bazel-discuss/GaLrGWQe-yc/XC6fQ6XWAgAJ

### CODE REVIEW

**Comment by robfig** [comment]
+@gkdn who did my other reviews

**Comment by robfig** [comment]
Can anyone provide feedback on this? cc @dslomov who most recently committed

**Comment by dslomov** [comment]
@gkdn will back on Monday 15th, probably that's the earliest when he will be able to respond.

**Comment by robfig** [comment]
OK, Thanks!

**Comment by robfig** [comment]
Hi @gkdn , just wanted to see if you had any feedback on this guy.

**Comment by robfig** [comment]
Weekly ping @gkdn

**Comment by robfig** [comment]
@gkdn

**Comment by gkdn** [comment]
Sorry, I need to be out for long time. Will take a look next week.

**Comment by gkdn** [comment]
I actually see examples of this in Google and seems like working fine.

Could you try following instead:
`defs = "--output_wrapper='(function(){%output%})();\n//# sourceMappingURL=testing.js.map'"`

**Comment by robfig** [comment]
Hi @gkdn, 
I'm not sure what the difference could be, but that does not work. 
Try checking out the commit (902e022d72add40de3638db889e3fda70d57e060) and applying this patch to do what you suggest:

```
--- a/closure/compiler/test/BUILD
+++ b/closure/compiler/test/BUILD
@@ -174,7 +174,9 @@ file_test(

 closure_js_binary(
     name = "multiline_output_wrapper_bin",
-    output_wrapper = "%output%\n//# sourceMappingURL=/app.js.map",
+    defs = [
+        "--output_wrapper='%output%\n//# sourceMappingURL=/app.js.map",
+    ],
     deps = [":empty_lib"],
 )
```

It results in an error:
```
Caused by: java.nio.file.NoSuchFileException: /# sourceMappingURL=/app.js.map
```

**Comment by gkdn** [comment]
@laurentlb Is there any difference how this is handled between blaze and bazel? I'm seeing plenty of new lines in google3 BUILD rules which suggests that this is working fine internally?

**Comment by robfig** [comment]
This PR was from my master branch, which I haven't left immobile for these past months, so it's rotted. I don't see a way to edit it, so I replaced it with another PR:
https://github.com/bazelbuild/rules_closure/pull/447

**Pull request closed without merging**
