### PR TITLE
Add support for import_prefix to protobuf rule

### LINKED ISSUE #390: Use of `strip_import_prefix` with `closure_proto_library`
[During discussion](https://github.com/bazelbuild/rules_closure/issues/388#issuecomment-499995862_) under #388, @Yannic suggested an issue be filed to enable support for `strip_import_prefix` in the `closure_proto_library` rule.

We have a tree of protos, defined via `proto_library`. When we try to create accompanying rules for these protos via `closure_proto_library`, Bazel fails to build them, with the following output:

```
ERROR: /private/var/tmp/_bazel_sam/.../external/schema/vendor/google/bq/BUILD.bazel:16:1: Generating JavaScript Protocol Buffer bq failed (Exit 1): protoc failed: error executing command 
  (cd /private/var/tmp/_bazel_sam/.../execroot/SomeWorkspace && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc -Ibazel-out/darwin-fastbuild/genfiles/external/schema -Ibazel-out/darwin-fastbuild/genfiles/external/com_google_protobuf '--js_out=import_style=closure,library=bq,add_require_for_enums:bazel-out/darwin-fastbuild/bin/external/schema/vendor/google/bq')
Execution platform: @bazel_tools//platforms:host_platform
Missing input file.
INFO: Elapsed time: 74.141s, Critical Path: 15.87s
INFO: 239 processes: 229 local, 10 worker.
FAILED: Build did NOT complete successfully
```

@gkdn, @Yannic asked that I tag you and ask that you assign this to him.

### PR DESCRIPTION
**Pull request by Yannic**
This change switches `closure_proto_library` to use the binary descriptors returned by `proto_library` instead of invoking `protoc` directly on the source files.

To reduce the code duplication for Starlark `*_proto_library` implementations, [rules_proto](https://github.com/Yannic/rules_proto) is used to generate JavaScript files from proto files.

Fixes #390

cc @sgammon

### CODE REVIEW

**Comment by sgammon** [comment]
@Yannic you are my hero, thank you!! i'll give it a shot

**Comment by sgammon** [comment]
@Yannic, sorry for the delay. i finally had a chance to check this out, and i figured out where to override it (we use `rules_closure` in a number of places in the project tree).

it does change the behavior, but, unfortunately, i get a crash of `rules_closure`. here's what i get as output:

```
ERROR: /private/var/tmp/_bazel_sam/.../external/project_with_protos/sources/.../BUILD.bazel:13:1: in @io_bazel_rules_closure//closure/protobuf:closure_proto_library.bzl%closure_proto_aspect aspect on proto_library rule @project_with_protos//sources/:proto_target: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_sam/.../external/project_with_protos/.../BUILD.bazel", line 13
		@io_bazel_rules_closure//closure/protobuf:closure_proto_library.bzl%closure_proto_aspect(...)
	File "/private/var/tmp/_bazel_sam/.../external/io_bazel_rules_closure/closure/protobuf/closure_proto_library.bzl", line 49, in _closure_proto_aspect_impl
		proto_common.lang_proto_aspect_impl(actions = ctx.actions, toolchain =...], <6 more arguments>)
	File "/private/var/tmp/_bazel_sam/.../external/build_bazel_rules_proto/proto/proto_common.bzl", line 141, in proto_common.lang_proto_aspect_impl
		actions.run(inputs = depset(plugin_files, tr...]), <5 more arguments>)
Index 0 out of bounds for length 0
```

Obviously, the key here is `Index 0 out of bounds for length 0`.

**Comment by Yannic** [comment]
@sgammon Thanks for trying this out! 

I've found some issues with `rules_proto` when external workspaces are involved while porting some more `*_proto_library` rules. This should be fixed in `rules_proto@head,` so let me just update this PR :).

I'm not sure if that'll also fix the bug you're seeing. From what I've seen, there isn't any array access near the location the crash happened, and the error message looks like the Exception Java throws for out-of-bounds array access. What version of Bazel are you using?

**Comment by laurentlb** [comment]
`Index 0 out of bounds for length 0`
I think I've seen the error before when the set of inputs is empty.

**Comment by Yannic** [comment]
Thanks! Creating a `proto_library` without `srcs` reproduced it.

**Comment by Yannic** [comment]
Blocked on https://github.com/bazelbuild/rules_proto/issues/6

**Comment by Yannic** [comment]
Withdrawing this for now. I'll send a new PR when [1] is accepted and implemented.

[1] https://docs.google.com/document/d/1u95vlQ1lWeQNR4bUw5T4cMeHTGJla2_e1dHHx7v4Dvg/edit

**Pull request closed without merging**
