### PR TITLE
Cleanup some of the depsets

### LINKED ISSUE #345: Fix incompatible_depset_union
As of Bazel 0.24, `rules_closure` does not build with: `--incompatible_depset_union` option:

```
ERROR: /home/davido/projects/davido_rules_closure/closure/webfiles/test/BUILD:29:1: in web_library rule //closure/webfiles/test:stuff: 
Traceback (most recent call last):
	File "/home/davido/projects/davido_rules_closure/closure/webfiles/test/BUILD", line 29
		web_library(name = 'stuff')
	File "/home/davido/projects/davido_rules_closure/closure/webfiles/web_library.bzl", line 88, in _web_library
		manifests += [manifest]
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
ERROR: Analysis of target '//closure/webfiles/test:stuff' failed; build aborted: Analysis of target '//closure/webfiles/test:stuff' failed; build aborted
INFO: Elapsed time: 11.700s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (211 packages loaded, 2431 targets configured)
FAILED: Build did NOT complete successfully (211 packages loaded, 2431 targets configured)
```

### PR DESCRIPTION
**Pull request by laurentlb**
Fix violations of `--incompatible_depset_union`

Fixes #345

### CODE REVIEW

**Comment by laurentlb** [comment]
cc @davido

**Comment by gkdn** [comment]
Sorry, I'm not going to be able to look at this earlier than next week.

**Comment by laurentlb** [comment]
All tests pass now with `--incompatible_depset_union`.

**Comment by davido** [comment]
Thanks!

**Pull request merged**
