### PR TITLE
Rename protobuf rules to closure_<lang>_proto_library format

### PR DESCRIPTION
**Pull request by hochhaus**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by jart** [comment]
Can you add a third commit providing a backwards compatible rule for the template ones only? E.g.

```python
def closure_template_java_library(**kwargs):
  print("Deprecated: use closure_java_template_library() instead, " +
        "closure_template_java_library will be removed in version 0.3.0")
  closure_java_template_library(**kwargs)
```

**Comment by jart** [comment]
Also would it be possible to break this into two pull requests?

**Comment by jart** [comment]
Mr. Jenkins: test this please

**Comment by jart** [comment]
LGTM. Thanks so much for sending this.

**Pull request merged**
