### PR TITLE
Use a sandboxed openssl.cnf file for phantomjs

### PR DESCRIPTION
**Pull request by AustinSchuh**
Debian buster has changed /etc/ssl/openssl.cnf far enough that the
openssl built into phantomjs can't parse it.  I found this out by
stracing a test run and watching it access /etc/ssl/openssl.cnf.  We
want bazel to not rely on anything outside the sandbox.  The error that
is returned otherwise is:

140302110000960:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140302110000960:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140302110000960:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140302110000960:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

Fixes: #351

### CODE REVIEW

**Comment by gkdn** [comment]
@laurentlb I have no idea on this one. You need to make judgement call.

**Comment by AustinSchuh** [comment]
Ping.

**Comment by xenu-xore** [comment]
I encountered the same problem on kali "2020.2"
First check that if you have openssl installed, then
sudo apt install openssl
I managed to solve this error by creating the OPENSSL_CONF variable.
1) **export OPENSSL_CONF = /etc/ssl/**
2) **Disconnect the terminals and reopen**

**Comment by 42510SR** [comment]
Hi, i am still getting an error, Error: html-pdf: Received the exit code '1'\nhtml-pdf: Evaluation - ReferenceError: Can't find variable: $\nStack:\n  at undefined\n 
not sure why can anyone help @AustinSchuh

**Pull request merged**
